### ISSUE TITLE
Suggestion: Always show the study abbreviation next to a study name

### ISSUE THREAD

**Issue by armish** [BioinformaticsFMRP/TCGAbiolinksGUI#11]
In particular, the Oncoprint Plot analysis tab fails to do this, which makes it harder to navigate down to a particular study. Given that many TCGA studies are centered around these abbreviations, it would be great to make sure that all parts of the GUI show these abbreviations for better navigation/selection.

**Comment by labrazil** [comment]
Fantastic suggestion. Thank you for your input. Sounds like a very doable
thing.

Cheers, Houtan


On Jan 20, 2017 4:53 PM, "B. Arman Aksoy" <notifications@github.com> wrote:

In particular, the Oncoprint Plot analysis tab fails to do this, which
makes it harder to navigate down to a particular study. Given that many
TCGA studies are centered around these abbreviations, it would be great to
make sure that all parts of the GUI show these abbreviations for better
navigation/selection.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BioinformaticsFMRP/TCGAbiolinksGUI/issues/11>, or mute
the thread

**Comment by tiagochst** [comment]
@armish Sure! I'll add this. Thanks for the suggestion.
