### ISSUE TITLE
File type selection works only partially

### ISSUE THREAD

**Issue by alevax** [BioinformaticsFMRP/TCGAbiolinksGUI#24]
If I select I want something from the project **TARGET-AML** it seems I can get results:

<img width="2061" alt="screen shot 2017-07-03 at 7 28 10 pm" src="https://user-images.githubusercontent.com/6618378/27810231-d869a8f6-6025-11e7-8b8f-a4d38f3f0c35.png">

But it is not working when I am selecting something else like **TARGET-NBL**:

<img width="2050" alt="screen shot 2017-07-03 at 7 28 33 pm" src="https://user-images.githubusercontent.com/6618378/27810234-df129b86-6025-11e7-8597-90dde46acb2a.png">

What could be the issue?

**Comment by tiagochst** [comment]
There might be a problem in GDC API. I'll need to open a ticket in GDC.

The [ Clinical data ](https://gdc-api.nci.nih.gov/cases/?pretty=true&size=151&filters=%7B%22op%22:%22and%22,%22content%22:[%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:[%22TARGET-NBL%22]%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:[%22Clinical%22]%7D%7D]%7D&format=json) that is requested only returns 7 samples instead of the 151.

**Comment by tiagochst** [comment]
Here is the GDC answer.

> We did some investigating and found that the file that was originally submitted to the GDC was incorrectly formatted and the import failed (this is why you only see 7 cases).  We plan to update this information in the next import of our data, but in the meantime you should be able to access this clinical information from the following link:

https://target-data.nci.nih.gov/Public/NBL/clinical/harmonized/TARGET_NBL_ClinicalData_20151124.xlsx

I'll update the code to consider this xlsx until It is not fixed.

**Comment by alevax** [comment]
@tiagochst , thanks. 
However, in the query I performed on the platform, I asked for the molecular data (count matrix), not the clinical data (that as far I understood is corrupted in the GDC API provider). I would say then that all the TARGET-NBL is non accessible until GDC will update their data/API.

**Comment by tiagochst** [comment]
I added an option to consider or not clinical data. If checked only samples with clinical data will be selected. Otherwise all samples will be selected. 
<img width="2288" alt="screen shot 2017-07-08 at 1 32 51 pm" src="https://user-images.githubusercontent.com/145529/27988882-06de7580-63e2-11e7-8678-6387cdca95c9.png">
